# -*- coding: utf-8 -*-
from RemoteNotesUIForm import *

class StartForm(UIForm):
    def setupUi(self):
        self.StartWindow.setObjectName("StartWindow")
        self.StartWindow.setEnabled(True)
        self.StartWindow.resize(820, 547)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(15)
        self.StartWindow.setFont(font)
        self.StartWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        with open("stylesheets/start_style.qss", "r") as stylesheet_file:
            self.StartWindow.setStyleSheet(stylesheet_file.read())
        self.StartWindow.setDocumentMode(False)
        self.StartWindow.setWindowFlag(QtCore.Qt.FramelessWindowHint)
        self.StartWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.startwidget = QtWidgets.QWidget(self.StartWindow)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(15)
        self.startwidget.setFont(font)
        self.startwidget.setObjectName("startwidget")
        self.frame = QtWidgets.QFrame(self.startwidget)
        self.frame.setGeometry(QtCore.QRect(70, 140, 630, 310))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 260, 480, 30))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Roboto Condensed")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(75, 130, 480, 40))
        self.lineEdit_2.setMouseTracking(False)
        self.lineEdit_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(75, 200, 220, 40))
        self.pushButton.setMouseTracking(False)
        self.pushButton.setTabletTracking(False)
        self.pushButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.frame)
        self.pushButton_2.setGeometry(QtCore.QRect(335, 200, 220, 40))
        self.pushButton_2.setMouseTracking(True)
        self.pushButton_2.setTabletTracking(True)
        self.pushButton_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButton_2.clicked.connect(self.StartWindow.close)
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(75, 70, 480, 40))
        self.lineEdit.setMouseTracking(False)
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.lineEdit.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setCursorPosition(0)
        self.lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.toolButton = QtWidgets.QToolButton(self.frame)
        self.toolButton.setGeometry(QtCore.QRect(560, 0, 71, 71))
        self.toolButton.setPopupMode(QtWidgets.QToolButton.DelayedPopup)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.clicked.connect(self.StartWindow.close)
        self.toolButton.setObjectName("toolButton")
        self.toolButton_2 = QtWidgets.QToolButton(self.frame)
        self.toolButton_2.setGeometry(QtCore.QRect(490, 115, 75, 65))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/eye.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.toolButton_2.setIcon(icon)
        self.toolButton_2.setIconSize(QtCore.QSize(100, 100))
        self.toolButton_2.clicked.connect(self.eye_click)
        self.toolButton_2.setObjectName("toolButton_2")

        self.lineEdit_2.setPlaceholderText("Password")
        self.pushButton.setText("LOGIN")
        self.pushButton_2.setText("EXIT")
        self.lineEdit.setPlaceholderText("Login")
        self.toolButton.setText("×")

        self.StartWindow.setCentralWidget(self.startwidget)
        QtCore.QMetaObject.connectSlotsByName(self.StartWindow)

    def eye_click(self):
        if self.lineEdit_2.echoMode() == 0:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        elif self.lineEdit_2.echoMode() == 2:
            self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)

    def wrong_login(self):
        self.lineEdit_2.setStyleSheet("border-bottom: 2px solid red;")
        self.lineEdit.setStyleSheet("border-bottom: 2px solid red;")

# app = QtWidgets.QApplication(sys.argv)
# startForm = StartForm()
# startForm.setupUi()
# sys.exit(app.exec_())